//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        [DisplayName("Mã hóa đơn")]
        public int ID { get; set; }
[DisplayName("Tên khách hàng")]
        public string CustomerName { get; set; }
[DisplayName("Địa chỉ")]
        public string CustomerAddress { get; set; }
[DisplayName("Email")]
        public string CustomerEmail { get; set; }
[DisplayName("Số điện thoại")]
        public string CustomerMobile { get; set; }
[DisplayName("Tin nhắn")]
        public string CustomerMessage { get; set; }
[DisplayName("Loại thanh toán")]
        public string PaymentMethod { get; set; }
[DisplayName("Ngày tạo")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
[DisplayName("Người tạo")]
        public string CreatedBy { get; set; }
[DisplayName("Trạng thái thanh toán")]
        public string PaymentStatus { get; set; }
[DisplayName("Trạng thái")]
        public bool Status { get; set; }
[DisplayName("Mã khách hàng")]
        public string CustomerId { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
