//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PostCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostCategory()
        {
            this.Posts = new HashSet<Post>();
        }
        [DisplayName("Mã loại bài viết")]
        public int ID { get; set; }
[DisplayName("Tên loại bài viết")]
        public string Name { get; set; }
[DisplayName("Tên khác")]
        public string Alias { get; set; }
[DisplayName("Mô tả")]
        public string Description { get; set; }
[DisplayName("Thứ tự")]
        public Nullable<int> DisplayOrder { get; set; }
[DisplayName("Ảnh")]
        public string Image { get; set; }
[DisplayName("Đề xuất")]
        public Nullable<bool> HomeFlag { get; set; }
[DisplayName("Ngày tạo")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
[DisplayName("Người tạo")]
        public string CreatedBy { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
[DisplayName("Trạng thái")]
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
    }
}
