//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Tags = new HashSet<Tag>();
        }
        [DisplayName("Mã bài viết")]
        public int ID { get; set; }
[DisplayName("Tên bài viết")]
        public string Name { get; set; }
[DisplayName("Tên khác")]
        public string Alias { get; set; }
[DisplayName("Mã loại bài viết")]
        public int CategoryID { get; set; }
[DisplayName("Ảnh")]
        public string Image { get; set; }
[DisplayName("Mô tả")]
        public string Description { get; set; }
[DisplayName("Nội dung")]
        public string Content { get; set; }
[DisplayName("Đề xuất")]
        public Nullable<bool> HomeFlag { get; set; }
[DisplayName("Nổi bật")]
        public Nullable<bool> HotFlag { get; set; }
[DisplayName("Lượt xem")]
        public Nullable<int> ViewCount { get; set; }
[DisplayName("Ngày tạo")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
[DisplayName("Người tạo")]
        public string CreatedBy { get; set; }

        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
[DisplayName("Trạng thái")]
        public bool Status { get; set; }
[DisplayName("Ảnh khác")]
        public string MoreImages { get; set; }
    
        public virtual PostCategory PostCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
