//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Tags1 = new HashSet<Tag>();
        }
        [DisplayName("Mã sản phẩm")]
        public int ID { get; set; }
[DisplayName("Tên sản phẩm")]
        public string Name { get; set; }
[DisplayName("Tên khác")]
        public string Alias { get; set; }
[DisplayName("Mã loại sản phẩm")]
        public int CategoryID { get; set; }
[DisplayName("Ảnh")]
        public string Image { get; set; }
[DisplayName("Ảnh khác")]
        public string MoreImages { get; set; }
[DisplayName("Giá")]
        public decimal Price { get; set; }
[DisplayName("Giá khuyến mại")]
        public Nullable<decimal> PromotionPrice { get; set; }
[DisplayName("Mô tả")]
        public string Description { get; set; }
[DisplayName("Nội dung")]
        public string Content { get; set; }
[DisplayName("Đề xuất")]
        public Nullable<bool> HomeFlag { get; set; }
[DisplayName("Nổi bật")]
        public Nullable<bool> HotFlag { get; set; }
[DisplayName("Lượt xem")]
        public Nullable<int> ViewCount { get; set; }
[DisplayName("Ngày tạo")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
[DisplayName("Người tạo")]
        public string CreatedBy { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
[DisplayName("Trạng thái")]
        public bool Status { get; set; }
[DisplayName("Bảo hành")]
        public Nullable<int> Warranty { get; set; }
[DisplayName("Thẻ")]
        public string Tags { get; set; }
[DisplayName("Số lượng")]
        public int Quantity { get; set; }
[DisplayName("Giá gốc")]
        public decimal OriginalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags1 { get; set; }
    }
}
