//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Slide
    {
        [DisplayName("Mã slide")]
        public int ID { get; set; }
[DisplayName("Tên slide")]
        public string Name { get; set; }
[DisplayName("Mô tả")]
        public string Description { get; set; }
        [DisplayName("Ảnh")]
        public string Image { get; set; }
[DisplayName("Thứ tự")]
        public Nullable<int> DisplayOrder { get; set; }
[DisplayName("Trạng thái")]
        public bool Status { get; set; }
    }
}
